Https client
Fundament-Software/keystone pull request #10
Opened 2023-01-13 22:49 UTC by ugandalf

Resolves #3. Adds hyper-tls as a dependency for https connector support. In its current form exposes https client via `https_client()` function. Some tests included in `path.rs`. Schema itself was modified to fix compile errors and structs moved inside `Path` capability as they were only used there.

2023-02-20 07:26 UTC, ErikMcClure requested changes

2023-02-20 07:26 UTC, ErikMcClure commented on core/schema/http.capnp
> +  path @1 (value :Text) -> (result :Path);
Please make this a `:List(Text)` and rename it "values" to reach parity with the path interface

2023-02-20 07:26 UTC, ErikMcClure commented on core/tests/http_test.rs
> +    ::core::result::Result::Err(::capnp::Error::unimplemented(
Please add a "finalize_domain" function to the domain interface that functions like the other finalize functions, and fill out the rest of this test accordingly.

2023-03-05 20:26 UTC, ugandalf commented on core/schema/http.capnp
> +  path @1 (value :Text) -> (result :Path);
Did that in 4f05c1e934bad7a07fbd9a3851f7884c8d2e8844 and I consider it resolved.

2023-03-05 20:46 UTC, ugandalf commented on core/tests/http_test.rs
> +    ::core::result::Result::Err(::capnp::Error::unimplemented(
"finalize_domain" was done in d361c45614cf91a95b8e828bd4d7180c7b8f628c, tests added in following three commits, but I'm uncertain about how the edge cases should be handled. As it is, paths ending with .. and such are valid, but don't refer to parent directory. Trying to use http escapes results in path ending with "&period%3B&period%3B". Also unsure if that's how protocol relative url breakout would look like, so review would be appreciated. Otherwise I also consider it resolved.

2023-03-13 06:25 UTC, aiverson reviewed
This test doesn't actually test what it says it does. This creates a new empty request to add things to the query string, then tests what query strings are in the newly created empty request, which is empty. It does not send anything to the provider and thus can't actually retrieve any data from it. The desired assurance is that there isn't a way to actually retrieve the already set query parameters from a path, to resist attempts to exfiltrate API tokens when handed an API url.

2023-03-13 07:48 UTC, aiverson commented on core/tests/http_test.rs
> +        assert_eq!(values.len(), 0);
this test also doesn't assure anything useful

2023-03-13 07:48 UTC, aiverson commented on core/tests/http_test.rs
> +
this doesn't actually assert anything

2023-03-13 07:48 UTC, aiverson commented on core/tests/http_test.rs
> +        values_builder.reborrow().set(0, "&period;&period;");
this is an xml entity and not an http url escape code.

2023-03-13 07:48 UTC, aiverson commented on core/src/http/path.rs
> +                "Can't include GET in verb whitelist, because it's not in the original one"
this error doesn't necessarily make sense.

2023-03-14 02:41 UTC, aiverson commented on core/tests/http_test.rs
> +        values_builder.reborrow().set(0, "&period;&period;");
please use the url library's facilities for handling url encoding to verify the safety.

2023-03-14 03:23 UTC, ugandalf commented on core/tests/http_test.rs
> +        let values = request.get().get_values()?;
I don't know how to prove impossibility of retrieving previous components via a test, when we don't even have a request that retrieves existing path data. This test was written by Erik and since I don't know what needs to be tested, I left it as-is. Do you want me to remove that test altogether or do you have something in mind?

2023-03-14 03:27 UTC, ugandalf commented on core/tests/http_test.rs
> +        assert_eq!(values.len(), 0);
Is the intention of that test to re-send existing request with changed data? Otherwise analogous to https://github.com/Fundament-Software/keystone/pull/10#discussion_r1134877641

2023-03-18 03:57 UTC, aiverson commented on core/tests/http_test.rs
> +        let values = request.get().get_values()?;
Yes, remove that part of the testing since there isn't a good place to actually test it. Instead, add comments to the capnp schema right next to where any methods that could exfiltrate data would be about how methods which permit the exfiltration need to not be added. That seems like about the best assurance we can do on that part for now.

2023-03-18 04:05 UTC, aiverson commented on core/tests/http_test.rs
> +        assert_eq!(values.len(), 0);
So, what this test is doing is creating an empty request and then checking that the request is empty. The closest thing to that which makes any sense would be trying to retrieve the tests from the remote and verifying that it doesn't provide any. But that's not doable because there is deliberately no method to do so. So it should be treated like the other requirement of not being able to acquire something, and turned into a comment to make a human stop and reconsider since it isn't practical to automatically test it. Perhaps the test can be changed to verify some other piece of functionality about the query strings, or just removed entirely.

2023-03-18 04:10 UTC, aiverson commented on core/tests/http_test.rs
> +
This is presumably supposed to be checking if putting / on the path permits navigating up the tree, but it needs to assert that whatever it gets is an error from the "/" being an invalid component of a path, or that the result of the get is something other than the expected root item and instead something down the requested path.

2023-03-29 03:32 UTC, ugandalf commented
I addressed all the points, I think - url is first constructed with `url` library, then it's converted to string and then that is straight up fed to `hyper::Uri`. In the current state I'm not using `percent-encoding` library - **do you want me to?** I'm also very unsure about corectness / what the intended behavior should be when adding those manually - when manually printing (via `println!("Path: {}", url);` at line 79 of path.rs), I currently get for example paths like `https://httpbin.org/get/%252E%252E?` - `?` added when unnecessary, `%25` being a code for `%`.

Also before merging I think duplication of `lib.rs` and `main.rs` should be resolved, but `lib.rs` can't be simply removed.

2023-04-02 03:07 UTC, ErikMcClure approved these changes

2023-04-02 03:07 UTC, merged