Implementing-cap_std
Fundament-Software/keystone pull request #17
Opened 2023-07-07 20:10 UTC by nivereno

Made changes based on conversation with Cloud, hopefully makes more sense

2023-07-08 22:04 UTC, ErikMcClure requested changes

2023-07-08 22:04 UTC, ErikMcClure commented on core/schema/cap_std.capnp
> +  new @0 (ambient_authority :AmbientAuthority) -> (clock :MonotonicClock);
interfaces returning themselves in capnproto are usually meaningless. Instead, all static methods like "new" that DO NOT use AmbientAuthority should be in a separate global interface. Maybe call this interface "capfs" or something. You can assume this global interface will magically be made available to users of this module.

2023-07-08 22:04 UTC, ErikMcClure commented on core/schema/cap_std.capnp
> +struct AmbientAuthority {
Make this an interface and move all methods that take AmbientAuthority as a parameter to this interface (and then remove the AmbientAuthority parameter, for obvious reasons).

2023-08-07 19:53 UTC, ErikMcClure requested changes
Mostly looks good, using capnp_let! will clean up the boilerplate.

2023-09-08 08:10 UTC, aiverson requested changes

2023-09-08 08:10 UTC, aiverson commented on core/schema/cap_std.capnp
> +  openWith @1 (read :Bool, write :Bool, append :Bool, truncate :Bool, create :Bool, createNew :Bool) -> (file :File);
Please aggregate these fields into a struct

2023-09-08 08:25 UTC, ErikMcClure requested changes

2023-09-08 08:25 UTC, ErikMcClure commented on core/src/cap_std_capnproto.rs
> +        todo!()
This is critically important to be both implemented and tested, or this cannot be merged.

2023-09-08 08:25 UTC, ErikMcClure commented on core/src/cap_std_capnproto.rs
> +        todo!()
This also needs to be finished before the PR is accepted.

2023-12-09 03:12 UTC, aiverson requested changes

2023-12-09 03:12 UTC, aiverson commented on core/schema/cap_std.capnp
> +  durationSince @0 (durationSinceUnixEpoch :Duration) -> (duration :Duration);
this should be taking a SystemTime

2023-12-09 03:12 UTC, aiverson commented on core/schema/cap_std.capnp
> +  checkedDurationSince @1 (earlierDurationSinceUnixEpoch :Duration) -> (duration :Duration);
and the next two should also be taking an Instant as an argument.

2023-12-09 03:12 UTC, aiverson commented on core/schema/cap_std.capnp
> +interface SystemTimeError {
This interface is unused, but it should probably not be an interface; since it's used to indicate when a clock ordering is in the wrong direction, it should probably be replaced with a union containing either a forward duration or a backward duration.

2023-12-12 09:18 UTC, ErikMcClure requested changes
Please utilize https://dwrensha.github.io/capnproto-rust/2022/11/03/0.15-release.html#capabilityserverset so that you can take Dir interface as a parameter and do useful things with it, which will allow you to more closely match the cap_std interface.

2023-12-12 09:18 UTC, ErikMcClure commented on core/schema/cap_std.capnp
> +  copy @6 (pathFrom :Text, pathTo :Text) -> (result :UInt64);
The argument that needs to be added here is `dirTo :Dir`, which `pathTo` should be relative to. This requires utilizing CapabilityServerSet in the implementation so that the implementation of Dir can recognize it's own capabilities and translate them back into an implementation: https://dwrensha.github.io/capnproto-rust/2022/11/03/0.15-release.html#capabilityserverset

2023-12-12 09:18 UTC, ErikMcClure commented on core/schema/cap_std.capnp
> +  hardLink @7 (srcPath :Text, dstPath :Text) -> ();
Again, this requires adding a `:Dir` argument, which will require the CapabilityServerSet object: https://dwrensha.github.io/capnproto-rust/2022/11/03/0.15-release.html#capabilityserverset

2023-12-17 13:57 UTC, ErikMcClure reviewed
Functionality looks good, just waiting on clarification for a few things from @aiverson

2023-12-17 13:57 UTC, ErikMcClure commented on core/schema/cap_std.capnp
> +interface AmbientAuthority {
Should this maybe be renamed to CapFS so it's more obviously the root capability or should it be left as AmbientAuthority? @aiverson

2023-12-17 13:57 UTC, ErikMcClure commented on core/src/cap_std_capnproto.rs
> +    static DIR_SET: RefCell<CapabilityServerSet<DirImpl, dir::Client>> = RefCell::new(CapabilityServerSet::new());
Rust does not allow associating statics with a specific struct, @aiverson is this an acceptable naming convention?

2023-12-17 18:07 UTC, aiverson commented on core/schema/cap_std.capnp
> +interface AmbientAuthority {
This is a builtin module, not a dynamically loaded module, so having a distinguished root capability isn't necessary for startup purposes. Not everything gets an ambient authority, and we wouldn't want to name things in a way that creates an expectation that everything does (naming it capfs would encourage a misunderstanding that in order to provide/use filesystem access the intended way one should pass capfs). I think Ambient Authority is a good name since it describes what it means and what it does clearly, and matches the underlying library which should help existing users migrate.

2023-12-18 08:46 UTC, ErikMcClure approved these changes

2023-12-18 13:35 UTC, ErikMcClure approved these changes

2023-12-18 13:35 UTC, merged