Implementing sturdyref saving and restoring
Fundament-Software/keystone pull request #20
Opened 2023-10-30 17:12 UTC by nivereno

2023-12-18 13:56 UTC, ErikMcClure requested changes
Need a calendar based approach on the scheduler.

2023-12-18 13:56 UTC, ErikMcClure commented on core/schema/scheduler.capnp
> +struct Duration {
This separation doesn't make sense. You should be able to schedule an event down to an arbitrary millisecond timestamp. You should also be able to repeat an event based on calendar durations, like "repeat every other week" or "repeat once a month" or "repeat once every half a year".

The first change that needs to happen here is that your timestamp should be a single, signed 64-bit integer representing the number of microseconds since the standard unix epoch. This should be used for `scheduleFor`. Then, for `scheduleForthenRepeat` you need an interval data structure that contains all possible calendar intervals that we might need. Year, Quarter, Month, Week, Day, plus a 64-bit microsecond counter. All of these would be added up (for example, you could have something repeat every 2 years 1 month and 2 weeks, if you really wanted that). Then, to find the next instance of the event, you take when it happened last, and ask a calendar library to get the timestamp of going 2 years, 1 month and two weeks into the future.

You should find a rust calendar library that can correctly perform a calculation like that. If you are unsure which library to use, find a couple and link them to me.

2023-12-18 13:56 UTC, ErikMcClure commented on core/schema/scheduler.capnp
> +  repeat @0 (listener :Listener, delay :Duration) -> (id :UInt8, cancelable :Cancelable);
I don't think this function makes sense in a distributed context, because "now" depends on the clock of the machine you ask, which might not be the one running it in the future. Worse, the packet requesting the event could be delayed by several seconds, which should not delay the intended repeat time in most cases. Better for a program to simply set `start` to the value of its own clock so the system will repeat it properly even if the initial packet is delayed.

Because of this, I would just delete this `repeat` function and rename `ScheduleForThenRepeat` to `repeat`, unless @aiverson thinks there's a reason we would need it.

2024-02-08 02:02 UTC, aiverson reviewed
The testing seems a little weak, but the implementation is fine for now; we won't want to use json with the actual database, but it seems to be a fine proof of concept.

2024-02-16 06:23 UTC, ErikMcClure approved these changes

2024-02-16 06:24 UTC, merged