Initial working test
Fundament-Software/keystone pull request #33
Opened 2024-07-02 13:21 UTC by ErikMcClure

Properly implements a stateful config with an auto-initialized cell using annotations.

This currently doesn't pass CI because all CI was broken by an unrelated change in capnproto-rs

2024-08-14 22:18 UTC, aiverson requested changes

2024-08-14 22:18 UTC, aiverson commented on core/src/config.rs
> +config = {{ nested = {{ state = [ "@keystone", "initCell", {{id = "myCellName"}}, "result" ], moreState = [ "@keystone", "initCell", {{id = "myCellName"}}, "result" ] }} }}
reminder: the keystone root capability the configuration uses needs to be different than the connection root capability provided to individual modules being launched.

2024-08-19 23:22 UTC, aiverson approved these changes

2024-08-20 00:41 UTC, merged

2024-08-20 01:21 UTC, nivereno approved these changes